// src/universal-schema/json/manual-generated-svelte/Form.svelte
<script lang="ts">
// Components
 import CrossPlatformWrapper from './components/CrossPlatformWrapper.svelte';
 import CrossPlatformLoadingWrapper from './components/CrossPlatformLoadingWrapper.svelte';
 import FormField from './FormField.svelte';

// Parsers
import { RulesEngine } from '../helpers/rules-parser';
import FormSideEffects from '../helpers/form.side-effects';

// Properties 

export let theme = '';
  
export let formData = {}; 
  
export let schema = {}; 
  
export let xhrSchema = {}; 
  
export let uiSchema = {}; 
  
export let validations = {}; 

export let prefixId = '';
            
export let submitOnEnter = () => {};
            
export let onChange = () => {};
            
export let onUpload = () => {};
            
export let onSubmit = () => {};
            
export let onStepNext = () => {};
            
export let onStepBack = () => {};
            
export let onStepSkip = () => {};
            
export let onStepReset = () => {};
            
export let formButtons = () => {};

export let actionButtonPos = '';
            
export let onCancel = () => {};
   
export let activityIndicatorEnabled = false; 

export let submitValue = '';

export let cancelValue = '';

export let inProgressValue = '';
   
export let disabled = false; 

export let cancelVariant = '';

export let submitVariant = '';
            
export let onError = () => {};
  
export let interceptors = {}; 

// Side Effects
const {
  isFormLoading,
  isFormSubmitting,
  hasPageLayoutTabs,
  hasPageLayoutSteps,
  formEvents: {
    onXHRSchemaEvent,
    onUpdateKeyProperty
  }
} = FormSideEffects({
  formData,
  schema,
  xhrSchema,
  uiSchema,
  validations,
  prefixId,
  submitOnEnter,
  onChange,
  onSubmit,
  onStepNext,
  onStepBack,
  onStepSkip,
  onStepReset,
  onError,
  interceptors,
});

const resolvedFacts = {
  isFormLoading,
  isFormSubmitting,
  hasPageLayoutTabs,
  hasPageLayoutSteps
};

// Rules
const { rulesParser } = RulesEngine({
  resolvedFacts
});

const isformloading = async () => await rulesParser({
  "all": [
    {
      "fact": "isFormLoading",
      "operator": "equal",
      "value": true
    },
    {
      "fact": "hasPageLayoutTabs",
      "operator": "equal",
      "value": true
    }
  ]
});

const formFieldProps = {
  schema, 
  data: formData, 
  uiSchema,
  xhrSchema,
  onChange,
  onXHRSchemaEvent,
  onUpdateKeyProperty,
  resolvedFormFacts: resolvedFacts,
}

</script>

<CrossPlatformWrapper>
    {#await isformloading()}
        <div> </div>
    {:then isformloading}                
        {#if isformloading}
        <CrossPlatformLoadingWrapper></CrossPlatformLoadingWrapper>
        {:else}
            <FormField {...formFieldProps}></FormField>
        
       {/if}
    {/await}
</CrossPlatformWrapper>

// src/cross-framework-wrapper/react/Form.tsx
// Types
import { FormProps } from '@core-types/Form.type';
import Framework from '@universal-schema/framework';

// State Machine Helpers
import { 
  useFormStateMachine,
  useFormEvents,
  useStepperEvents,
  getHashCodeFromXHRDef,
} from '@helpers/state-machine/form/hooks';

// Initial Contexts
import { LoadingContext, EventContext, StepperContext } from '@helpers/context';

// Internal
import FormField from './FormField';

const {
  React,
  nanoId: generate,
} = Framework.library;

const {
  internal: {
    CrossPlatformWrapper,
    CrossPlatformLoadingWrapper,
    FormButtons,
  },
  styles: {
    FormStyles: formStyles,
    defaultTheme,
  }
} = Framework.uiFramework;

const Form = ({
  theme,
  formData: originalFormData,
  schema = {},
  xhrSchema = {},
  uiSchema: originalUISchema = {},
  validations,
  prefixId,
  submitOnEnter,
  onChange,
  onUpload,
  onSubmit,
  onStepNext: givenOnStepNext,
  onStepBack: givenOnStepBack,
  onStepSkip: givenOnStepSkip,
  onStepReset: givenOnStepReset,
  formButtons,
  actionButtonPos,
  onCancel, 
  activityIndicatorEnabled,
  submitValue,
  cancelValue,
  inProgressValue,
  disabled, 
  cancelVariant,
  submitVariant,
  onError,
  interceptors,
  ...rest 
}: FormProps) => {
  const {
    formInfo: {
      formSchemaXHR,
      uiData,
      uiSchema,
      formData,
      activeStep,
      xhrProgress,
      validation,
    },
    loadingState,
    buttonDisabled,
    stateMachineService,
  } = useFormStateMachine({
    xhrSchema,
    interceptors,
    originalFormInfo: {
      schema,
      uiSchema: originalUISchema,
      formData: originalFormData,
      validations,
      xhrSchema,
    },
    effects: {
      onChange,
      onError,
    },
  });

  // Form Events
  const {
    onTabChange,
    onMoveItemUp,
    onMoveItemDown,
    onDeleteItem,
    onAddItem,
    onAddNewProperty,
    onRemoveProperty,
    onUpdateKeyProperty,
    onFormValuesChange,
    onFormSubmit,
    onXHRSchemaEvent,
    handleKeyEnter,
  } = useFormEvents({
    validation,
    stateMachineService,
    formData,
    schema,
    uiData, 
    uiSchema, 
    xhrSchema,
    interceptors,
    submitOnEnter,
    onSubmit,
  });

  // Stepper Events
  const {
    onStepNext,
    onStepBack,
    onStepSkip,
    // onStepReset,
  } = useStepperEvents({
    stateMachineService,
    validation,
    formData,
    schema,
    uiData, 
    uiSchema,
    xhrSchema,
    interceptors,
    onSubmit,
    givenOnStepNext,
    givenOnStepReset,
    givenOnStepBack,
    givenOnStepSkip,
  });

  const classes = formStyles();
  const id = prefixId || generate();

  const hashRef = getHashCodeFromXHRDef({
    eventName: 'onload',
    fieldPath: 'ui:page',
    xhrSchema,
  });

  const onSubmitHashRef = getHashCodeFromXHRDef({
    eventName: 'onsubmit',
    fieldPath: 'ui:page',
    xhrSchema,
  });

  const isFormLoading = xhrProgress && hashRef && xhrProgress[hashRef];

  const isFormSubmitting = xhrProgress && onSubmitHashRef && xhrProgress[onSubmitHashRef];

  const hasPageLayoutTabs = uiSchema['ui:page'] 
                              && uiSchema['ui:page']['ui:layout'] 
                              && uiSchema['ui:page']['ui:layout'] === 'tabs';

  const hasPageLayoutSteps = uiSchema['ui:page'] 
                              && uiSchema['ui:page']['ui:layout'] 
                              && uiSchema['ui:page']['ui:layout'] === 'steps';

  const RenderFormButtons = () => (
      <FormButtons
        onSubmit={(callback: any) => onFormSubmit(callback)}
        disabled={buttonDisabled}
        submitValue={submitValue}
        cancelValue={cancelValue} 
        onCancel={onCancel}
        cancelVariant={cancelVariant}
        submitVariant={submitVariant}
        classes={classes}
        activityIndicatorEnabled={activityIndicatorEnabled}
        inProgress={uiSchema['ui:page']?.isFormSubmitting || isFormSubmitting}
        inProgressValue={uiSchema['ui:page']?.inProgressText}
      />
  );
  
  return (
    <CrossPlatformWrapper
      classes={classes}
      uiSchema={uiSchema}
      defaultTheme={defaultTheme}
      theme={theme}
      RenderFormButtons={RenderFormButtons}
      actionButtonPos={actionButtonPos}
      hasPageLayoutSteps={hasPageLayoutSteps}
      isFormLoading={isFormLoading}
    >
      <LoadingContext.Provider value={loadingState}>
        <StepperContext.Provider value={[activeStep, buttonDisabled] as any}>
            <EventContext.Provider value={onUpload}>
              {
                  isFormLoading && !hasPageLayoutTabs ? <CrossPlatformLoadingWrapper /> : (
                    <FormField
                      path={''}
                      data={formData}
                      uiData={uiData}
                      schemaVersion={schema.version}
                      schema={{
                        ...schema,
                        ...formSchemaXHR,
                      }}
                      uiSchema={uiSchema}
                      xhrSchema={xhrSchema}
                      definitions={schema.definitions}
                      interceptors={interceptors}
                      xhrProgress={xhrProgress}
                      id={id}
                      onChange={onFormValuesChange}
                      onXHRSchemaEvent={onXHRSchemaEvent}
                      onSubmit={onFormSubmit}
                      validation={validation}
                      onKeyDown={handleKeyEnter}
                      onMoveItemUp={onMoveItemUp}
                      onMoveItemDown={onMoveItemDown}
                      onDeleteItem={onDeleteItem}
                      onAddItem={onAddItem}
                      onAddNewProperty={onAddNewProperty}
                      onRemoveProperty={onRemoveProperty}
                      onUpdateKeyProperty={onUpdateKeyProperty}
                      onNext={onStepNext}
                      onBack={onStepBack}
                      onSkip={onStepSkip}
                      onTabChange={onTabChange}
                      isSubmitDisabled={buttonDisabled}
                      {...rest}
                    />
                  )
              }
            </EventContext.Provider>
          </StepperContext.Provider>
      </LoadingContext.Provider>
    </CrossPlatformWrapper>
  );
};

export default Form;
